### ISSUE TITLE
submision broken Error: "parameter 1 to be string, array given in" 

### ISSUE THREAD

**Issue by appnitus** [pods-framework/pods-gravity-forms#29]
I am getting this error:
"Warning: strlen() expects parameter 1 to be string, array given in /home/server/public_html/test/wp-content/plugins/pods/classes/fields/text.php on line 202"
is shown more than once on a form submision, I am almost sure that is related to combo boxes, radio or checkboxes in the form but I am selecting/passing only one value each time while filling the form, I am using text fields on my database table ( I am using pods to store on an external table)

I know that this is a free plugin and I am very grateful but I wonder if somebody got the same issues and know a fix least know a temporal tweak to making it work until a future release 

or at least Is there any way to know what fields are causing the issue? is happening on a long form

**Comment by appnitus** [comment]
I got that error with the following configuration: Wordpress 4.1.1 / Gravityforms 1.9.3 Developer /  Pods 2.5.1.1 / Pods Gravity Forms Add-On Version 1.0 Alpha 9

**Comment by sc0ttkclark** [comment]
Try the latest version of Pods Gravity Forms (1.0 Alpha 10) https://github.com/pods-framework/pods-gravity-forms/archive/master.zip and the latest version of Pods (2.5.2 Beta) http://pods.io/latest/

**Comment by sc0ttkclark** [comment]
Potentially fixed by https://github.com/pods-framework/pods-gravity-forms/commit/e982f82cfacba69ed1bdb5c9b959b07919069cbb -- needs testing to confirm.

**Comment by StaggerLeee** [comment]
I have this problem when using CF7 checkboxes with **default:get**. I need it to mark box checked via links when visitor come to form from other Page. So this small problem is still around.

Other Info is as Issue Author explained.

**Comment by StaggerLeee** [comment]
Solved it by switching to textarea and styling field exactly as text field. Not so important for me as I use fields for something very special and they are not editable in backend.
